### ISSUE TITLE
Create logic for determining what is the best possible word to write 🤡 

### ISSUE THREAD

**Issue by arnenator** [Arneproductions/Scrabble-Project#18]
Create move function that takes the following:
- The updated Board
- The current hand

It should take board and hand into account and then find possible words in the gaddag.

TODO:
- [ ] Validate that a play can actually be played, taking into consideration the other words on the board
- [ ] Validate that the found word is actually a word (Using the boolean given by the gaddag) (This could also be used to find earlier possible words)
- [x] Figure out where to start and which direction to look in
- [ ] Fix all the TODO's
- [ ] Handle blanks
- [ ] Take points into consideration (For more points at the hand in, AKA it's optional)

**Comment by albe2669** [comment]
Possibly explore the Gaddag whitepaper for heuristics it suggests.

https://ericsink.com/downloads/faster-scrabble-gordon.pdf
